# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'ja-JP'

reviews:
  profile: 'chill'
  high_level_summary: true
  review_status: true

  auto_review:
    enabled: true
    drafts: false

  # PRのChecksに status を出す（Rulesetのrequired checksに使える）
  commit_status: true
  fail_commit_status: false

  # Walkthroughに "Prompt for AI Agents" を含める（Codexに渡しやすい）
  enable_prompt_for_ai_agents: true

  # ノイズになりやすいものだけ除外（! で除外）
  path_filters:
    - '!node_modules/**'
    - '!.next/**'
    - '!out/**'
    - '!build/**'
    - '!dist/**'
    - '!coverage/**'
    - '!playwright-report/**'
    - '!test-results/**'
    - '!backend/.venv/**'
    - '!backend/.ruff_cache/**'
    - '!backend/.pytest_cache/**'
    - '!**/__pycache__/**'
    - '!**/*.log'
